### ISSUE TITLE
Feature: a PR comment associated with a single run

### ISSUE THREAD

**Issue by gregoryduckworth** [turing85/publish-report#38]
Just wanted to say thank you for this action, it's a great action and am using it extensively! 

I do have a small request in that I have several test suites all making use of the action and post to a PR. However it would be nice if a Github Action run would be it's own action. I know that sounds confusing but my use case is:

- I develop a branch and push changes 
- Test suites run and post comments
- Whilst this is going on, I notice a syntax issue
- Quickly update the PR and subsequently push
- It updates the comment on the PR with test results from both runs. (What would be nice is each run was associated to a single comment)

eg:

- Comment for PR - Run #123
  - Test Result A - Passed
  - Test Result B - Failed
- Comment for PR - Run #124
  -  Test Result A - Passed
  - Test Result B - Passed

**Comment by turing85** [comment]
Hey!

I haven't tested the full flow, but as far as I can see, it should be possible to do what you want.

So as you most probably already know, this action is just an aggregate action, orchestrating other actions. The action responsible for posting comments is [`marocchino/sticky-pull-request-comment`](https://github.com/marocchino/sticky-pull-request-comment). It identifies the comment to create/update through the [`header`-input](https://github.com/marocchino/sticky-pull-request-comment/blob/main/action.yml#LL14). The input [`comment-header`](https://github.com/turing85/publish-report/blob/main/action.yml#L50) of this action (`publish-report`) is "forwarded" to `header` in `marocchino/sticky-pull-request-comment`. 

What you'd need to do is access the workflow run id (which should be accessible through variable `run_id` in [the `github` context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)) and use it it `comment-header`. You can also use this variable in [`comment-message-recreate`](https://github.com/turing85/publish-report/blob/main/action.yml#LL78) to (visibly) identify the run.

**Comment by turing85** [comment]
I discovered and fixed #39 while I coded up a small example. I released [v1.0.8](https://github.com/turing85/publish-report/releases/tag/v1.0.8) containing the fix.

 [Here](https://github.com/turing85/advent-of-code-2022/pull/97) is a POC of how one could achieve what you want (if I understood you correctly). Please notice that you'll need v1.0.8, since the bug fixed in #39 will prevent this solution from working properly. ~~Sadly, github is experiencing issues righ now. I'll clean up the example later.~~ Example is now cleaned-up and shows multiple runs, with links to the corresponding runs.

Please let me know if this is what you want. And you are always welcome to extend the documentation and, for example, link to one of your repositories as reference for others.

**Comment by gregoryduckworth** [comment]
This looks great @turing85! I've created a new PR which updates the default to point to the url of the action as default as well.

**Comment by turing85** [comment]
Can this issue be closed? :slightly_smiling_face:

**Comment by gregoryduckworth** [comment]
Thanks @turing85, it sure can!

**Comment by turing85** [comment]
@gregoryduckworth [v1.0.9](https://github.com/turing85/publish-report/releases/tag/v1.0.9), containing the changes of #43, has been released.
